const Discord = require('discord.js');

exports.run = async (bot, message, args) => {
    var dogruluk = [
      'Telefonunda arattığın en son şey nedir ?',
      'Bir sabah karşı cins olarak uyansaydın ilk yapacağın şey ne olurdu ?',
      'Sence bu odadaki en kötü giyinen kişi kim ?',
      'Hiç bir asansörde osurdun mu ?',
      'En son ne zaman bir havuza işedin ?',
      'Şuanda ne renk iç çamaşırı giyiyorsun ?',
      'Telefonunda en son attığın mesaj nedir ?',
      'Eğer çıplak kalmak ile kafanın üzerinde aklından geçen her düşüncenin yazılı olarak yansıyacağı bir baloncukla yaşamak arasında bir seçim yapmak zorunda kalsaydın hangisini seçerdin ?',
      'Sokakta yere bir şey düşürdüğünde hiç bir şey olmamış gibi alıp ağzına attın mı ?',
      'Hiç sümük yedin mi ?',
      'Şu kişiyi seviyor musun ? (O kişinin sevdiğinden şüphe ettiğiniz bir kişinin adını söyleyin)',
      'Bu odada “keşke onun yerinde olsaydım” dediğin bir kişi söyler misin ?',
      'Tuvaletini yaparken düşündüğün bir kaç şey söyler misin ?',
      'Küçükken hiç bir çizgi film karakterine aşık olmuş muydun ?',
      'Korku filmlerinde gözlerini ellerinle kapattığın oldu mu ?',
      'Hiç aynada öpüşme pratiği yaptığın oldu mu ?',
      'En saklı hazzını söyle ?',
      'En kötü huyun nedir ?',
      'Hiç birinin yanlışlıkla seni çıplak gördüğü oldu mu ?',
      'Hiç camdan bir kapıya dikkatsizce kapı yok sanarak çarptığın oldu mu ?',
      'Duşta hangi şarkıyı söylersin ?',
      'Duştayken işer misin ?',
      'En son ne zaman yanlışlıkla üzerine işedin ?',
      'Dışarıda yaşadığın en utanç verici an neydi ?',
      'İnsan içinde hiç yanlışlıkla sesli bir şekilde osurduğun oldu mu ?',
      'Tuvaletini yaptın ve o an fark ettin ki wc de tuvalet kağıdı yok ne yapardın ?',
      'Başkası tarafından görüldüğünde utanacağın google aratma geçmişin nedir ?',
      'Hiç kendi seksi fotoğraflarını çektin mi ?',
      'Hiç peluş bir oyuncakla yattın mı ?',
      'Gizli platoniğin kim ?',
      'Sence (odadaki birinin adını vererek) tatlı biri mi ?',
      'Bu odada en az sevdiğin kişi kim ?',
      'Duşta en çok çalmayı sevdiğin şarkı nedir ?',
      'Sence bu odadaki en seksi kişi kim ?',
      'Görünüşüne bir puan vermen gerekse 1 ile 10 arasından kaç verirdin ?',
      'Hayalindeki kız/erkek nasıl biri ?',
      'Hangisini tercih ederdin ? Düşün ki ……… ile seks yaptın ama kimse bilmiyor. Ancak …….. ile seks yaptın ve herkes kulaktan kulağa bunu konuşuyor !',
      'Benim hakkımda sevmediğin bir şey söyle.',
      'Eğer yangın çıkmış bir binadan insanları kurtarıyor olsaydın ve bu odadaki bir kişiyi kurtaramayarak geride bırakmak zorunda olsaydın, o kişi kim olurdu ?',
      'Şuanki sevgilinle evlenir miydin ?',
      'Bir iç çamaşırı kaç gün giyiyorsun ?',
      'Hiç osurup suçu başkasına attın mı ?',
      'Yaptığın en yasa dışı şey neydi ?',
      'Anneni mi daha çok seviyorsun babanı mı ?',
      'Bir milyon lira verseler en sevdiğin evcil hayvanını köpek maması yapmaları için satar mıydın ?',
      'En gıcık olduğun şey nedir ?',
      'Çok güzel/yakışıklı olsa bir uzaylıyla sevişir miydin ?',
      'Eğer birden fazla eşle evlenebilseydin ? Kimleri seçerdin ?',
      'Düşün ki 100 kişinin hayatını kurtacaksın ama kimse bilemeyecek. Ya da kimseyi kurtarmayacaksın ama herkes ömrün boyunca seni taktir ediyor olacak. Hangisini seçerdin ?',
      'Ömrünün sonuna kadar dinlemek için tek bir şarkı seçebilecek olsaydın hangisini seçerdin ?',
      'Sence bu odadaki kimle çıkmazdın ? Neden ?',
      'Kışın ortasında evinde internetsiz yaşamayı mı, ısıtma sistemi olmadan yaşamayı mı tercih ederdin ?',
      'Eğer tekrar dünyaya gelseydin, doğmak için hangi yılı seçerdin ?',
      'Eğer bir zaman makinen olsaydı ve geçmişe gidip yaptığın tek bir şeyi silebilecek olsaydın, neyi silerdin ?',
      'Hiç aldatıldın mı ?',
      'Görünmezlik gücün olsaydın ne yapardın ?',
      'Birine alıcı gözle dikkatli bir şekilde yaparken o kişi tarafından aniden fark edildiğin oldu mu ?',
      'Kendini en ezik hissettiğin an hangisiydi ?',
      'Gördüğün en sapık rüyayı anlat !',
      'Hiç sosyal medyaya yükleyip sonra pişman olup sildiğin bir fotoğraf oldu mu ?',
      'En büyük saçma korkun nedir ?',
      'Duş alırken işer misin ?',
      'Dünya haftaya sona erecek olsa, hangi yasa dışı şeyleri yapardın ?',
      'Hala yapmaya devam ettiğin en garip şey nedir ?',
      'Özendiğin ve onun gibi olamam dediğin kişi kimdir ?',
      'Sana takılan en rahatsız edici lakap neydi ?',
      'Seni insanlar içinde en son utanç verici bir duruma düşüren şey neydi ?',
      'Eğer dizi karakteriyle sevişebilecek olsaydın, kimi seçerdin ?',
      'Biriyle buluşmamak için hastayım diye yalan attığın olduğu mu ? İsim ver !',
      'Bir oturuşta mideni en çok tıkabasa doldurduğun zaman neler yemiştin ?',
      'Hiç kazıklandın mı ? Nasıl ?',
      'Sadece evde tek başınayken yaptığın en garip şey nedir ?',
      'Bir günde en çok kaç selfie çektin ?',
      'Kendini rezil ettığin bir anını anlat !',
      'En büyük hayal kırıklığını anlat !',
      'Enayilik yaptığın bir anı anlat !',
      'Dişini fırçalamadan geçirdiğin en uzun süre ?',
      'Duş almadan yaşadığın en uzun süre ?',
      'Yapmaman gereken bir şeyi yaparken yakalandın mı? O şey neydi ?',
      'Vücudunun en çok neresini seviyorsun ?',
      'Vücudunda en sevmediğin yer neresi ?',
      'Hiç bitlendin mi ?',
      'En son ne zaman altına kaçırdın ?',
      'Hakkında kimsenin bilmediği şey nedir ?',
      'Geçmişe baktığında keşke onunla çıkmasaydım dediğin biri ?',
      'Hiç bir arkadaşının sevgilisinden hoşlandığın oldu mu ?',
      'Okuldan / iş yerinden biriyle sevişecek olsaydın kimi seçerdin ?',
      'Reddedildiğinde en içini acıtan kişi kimdi ?',
      'Hiç kendinden 10 yaş büyük birine aşık oldun mu ?',
      'Sütyen bedenin ne ?',
      'Bababanne donu giyer misin ?',
      'Aşık olduğun ünlü kimdi ?',
      'Seksi giyinmek istesen nasıl giyinirdin ?',
      'Vücudunda bir yerine estetik ameliyat yaptırmak isteseydin nerede yaptırırdın ?',
      'İlk öpücüğünü anlat !',
      'Hayatında en çok kıskandığın kişi kimdir ?',
      'Okulda / iş yerinde keşke onun yerinde olaydım dediğin gibi kimdir ?',
      'Hiç ilk buluşmada seviştin mi ?',
      'Sınıfındaki en yakışıklı 3 kişiyi say !',
      'Gelecekte kaç çocuğa sahip olmak istersin ?',
      'Son zamanlarda en çok nefret ettiğin kişi kimdir ?',
      'Eğer ıssız bir adada kalsaydın okuldan / iş yerinden kiminle beraber kalmak isterdin ?',
      'Diğer insanlar tarafından öğrenilmesinden korktuğun bir sırrını söyle !',
      'Hiç salak yerine koyduldun mu ? Nasıl ?',
      'İnternetten en son ne zaman açık saçık bir film izledin ?',
      'Karşı cinste en seksi bulduğun şey nedir ?',
      'Senden daha kısa biriyle çıkar mıydın ?',
      'Çıplak görmek istemediğin birini söyle !',
      'Keşke görmeseydim dediğin bir şeyi söyle.',
      'Sadece bir günlüğüne cinsiyet değiştirebilseydin neler yapardın ?',
      'Asla yemem dediğin bir yemek söyle !',
      'Eğer araban ıssız bir yerde bozulsaydı, bu odada bulunanlardan en son yardım isteyeceğin kişi kim olurdu ? Neden ?',
      'Unutmayı çok istediğin utanç verici bir anını anlat !',
      'En iyi arkadaşın sevgiline aşık olduğunu söylese ne yapardın ?',
      'Eğer arkadaşının sevgilisinin onu aldattığını öğrenseydin ne yapardın ?',
      'Bu odadaki (bir kişinin adını vererek) kişisini ilk gördüğünde onun hakkındaki ilk izlenimin neydi ?',
      'Hiç arkadaşının bir sırrını başkasıyla paylaştın mı ?',
      'Bu odadaki herkesi seksiliğe göre 1 ile 10 arasında puanla !',
      'İyi bir arkadaşına söylediğin bir yalanı paylaş !',
      'Seni yalan makinasına soksalar ortaya çıkacağından en çok korktuğun yalanın nedir ?',
      'Hiç yakın bir arkadaşını sattın mı ? Neden ?',
      'Kiminle arkadaşlığını sonsuza kadar kesmek isterdin ? Neden ?',
      'Ona (odadaki bir kişiyi göstererek) bakınca aklında beliren ilk düşüne ne ?',
      'Şuan sevdiğin ama ona karşı adım atamadığın biri var mı ?',
      'Kaç farklı kişiyle seviştin ?',
      'Hiç batıl inancın var mıdır ?',
      'Hayatında kaç farklı kişiyle öpüştün ?',
      'Seni seksual olarak en çok heyecanlandıran şey nedir ?',
      'Hiç birine açık saçık fotoğraflar yolladın mı ?',
      'Hiç birinden açık saçıp fotoğraflar aldın mı ? Kimden ?',
      'Hiç öğretmenine aşık olmuş muydun ?',
      'Kiminle öpüşmek en çok hoşuna gitmişti ?',
      'Birine yanlışlıkla gönderdiğin en utanç verici mesaj neydi ?',
      'Sahip olduğun en kötü alışkanlık nedir ?',
      'Kimsenin bilmesini istemediğin sahip olduğun en kötü özellik nedir ?',
      'Sosyal medyada sürekli olarak gizlice takip ettiğin / stalk yaptığın kişi kimdir ?',
      'Odadaki bir kişiyle sevişmek zorunda olsaydın kimi seçerdin ?',
      'Aradan yıllar geçse bile hatırladığında seni sinirlendiren şey nedir ?',
      'Birinden kötü bir şekilde reddedildin mi ? Nasıl ?',
      'Sevgilini hiç aldattın mı ?',
      'En son ne zaman ağladın ?',
      'Hiç timsah gözyaşları döktün mü ?',
      'Hiç bir arkadaşının sevgilisini çalmaya yeltendin mi ?',
      'Eğer bu odadaki biri seni 5 saniyeliğine çıplak görmek zorunda olsa kimi seçerdin ?',
      'Sence buradaki en eğlenceli karaktere sahip olan kişi kim ?',
      'Biriyle buluşmaya gitmeden önce aynada kendini kaç defa kontrol edersin ?',
      'Cinsel fantezilerinden bir tanesini söyle !',
      'Şuana kadar yaptığın en flörtöz hareket neydi ?',
      '(Odadaki birini göstererek) Onunla ilgili 1 iyi ve 1 kötü şey söyle !',
      'Şuana kadar ettiğin en pis küfür neydi ?',
      'Yaptığın en çılgınca şey neydi ?',
      'Üstsüz şekilde güneşlenir miydin ?',
      'Eğer bu odadan biriyle evlenseydin kimi seçerdin ?',
      'İnstagramdan 5 kişi silecek olsan kimleri silerdin ? İsim ver.',
      'Senin arkadan söylenen en kötü laf neydi ?',
      'Hiç yanlışlıkla bir hayvanın üzerine oturdun ?',
      'Hiç bir öğretmenine aşık oldun mu ? Kime ?',
      'Hiç birini rızası dahilinde taciz ettin mi ?',
      'Son zamanlarda seni çırılçıplak gören biri oldu mu ?',
      'İnternette arattığın en terbiyesiz şey neydi ?',
      'Hiç aynı cinsiyetten birinden etkilendin mi ?',
      'Hiç röntgencilik yaptın mı ?',
      'Genç ve mutlu şekilde ölmeyi mi tercih ederdin, yaşlı ve mutsuz şekilde mi ?',
      'Hiç sarhoşken biriyle seviştin mi ?',
      'Hiç bir çifti sinsice ayırmaya çalıştın mı ?',
      'Hiç bir arkadaşını sevgilisini terk etmesi için doldurmaya çalıştın mı ?',
      'Arkadaşının eski sevgilisiyle takıldığın oldu mu ?',
      'Hiç bir hayvana kötü davrandın mı ?',
      'Hiç asılsız bir dedikodu yaydın mı ?',
      'Acımasızca davrandığın bir anını anlat !',
      'Yaptığın en kötü davranış nedir ?',
      'Suçlu sayılmayacağını bilsen kimi öldürürdün ?',
      'Sence okulda / iş yerinde en güzel / yakışıklı kişi kim ?',
      'Hiç bir obje üzerinde öpüşme pratiği yaptın mı ?',
      'Gerçekleşeceğini bilsen yapacağın tek dilek ne olurdu ?',
      'Kendinin gerizekalı olduğundan şüphelendiğin bir an oldu mu ?',
      'Ailenin yaptığını bilmediği bir şey söyle !',
      'Telefonun olmadan 1 ay hayatta kalabilir miydin ?',
      'Biri hakkında dedikodu yaydın mı ?',
      'Hiç tinder üzerinden eşleşip biriyle seviştin mi ?',
      'Sence instagram profilinde yansıttığın kişiye yüzde kaç oranında benziyorsun ?',
      'Birinden ödünç alıp da vermediğin şey nedir ?',
      'Normalde yapmayacağın ancak sırf instagramda daha fazla beğeni almak için yaptığın şey nedir ?',
      'Sence boyut mu önemli yoksa işlev mi ?',
      'Hiç sevgilisi olduğunu bildiğin biriyle takıldın mı ?',
      'Sonradan iyi ki yapmamışım dediğin kötü bir kararını açıklar mısın ?',
      'Eski sevgilinin sosyal medya profilini hangi sıklıkla ziyaret ediyorsun ?',
      'En büyük kişisel güvensizliğin nedir ?',
      'Hiç söylemesi ayıp bir vücut uzvunu ölçtün mü ? Kaç santim çıktı ?',
      'Kasti olarak kavga çıkardın mı ? Neden ?',
      'Alkollüyken yaptığın en utanç verici şey neydi ?',
      'Bir sırrını söyle !',
      'Bir şey itiraf et !',
      'Hiç birine psikolojik işkence yaptın mı ?',
      'Sosyal medyada en çok gözetlediğin kişi kimdir ?',
      'Telefonunda en son aradığın şey neydi?',
      'Birisi kız arkadaşın / erkek arkadaşından ayrılmak için sana 1 milyon tl önerseydi, yapar mıydın?',
      'Bu odadaki en az kimi seviyorsun ve neden?',
      'Hiç sınıfta yüksek sesle genirdin mi?',
      'Yerden bir şeyi alıp hiç yedin mi?',
      'Bu odada en kötü giyinen kişi kimdir?',
      'Yılan, kurbağa gibi şeylerden yemek zorunda kaldın mı?',
      'Bir gün karşı cins olarak uyanırsan, ilk yapacağın şey nedir?',
      'Hiç havuzda işedin mi?',
      'Sence bu odadaki en kötü giyinen kişi kimdir?',
      'Asansörde hiç gaz kaçırdın mı?',
      'Tuvalette otururken aklınıza gelen şeyler nelerdir?',
      'Büyüyen hayali bir arkadaşınız var mıydı?',
      'En kötü alışkanlığınız nedir?',
      'Burnunu karıştırır mısın?',
      'Banyoda şarkı söyler misin?',
      'Hiç üzerine işedin mi?',
      'Toplumda en utanç verici anınız neydi?',
      'Aynada kendinle hiç konuştun mu?',
      'Web geçmişinizi, birileri görürse utanacağınız şey ne olurdu?',
      'Uykunda konuşur musun?',
      'Gizli aşkın kim?',
      'Benim hakkımda neyi sevmiyorsun?',
      'Şu an ne renk iç çamaşır giyiyorsun?',
      'Son attığın mesaj neydi?',
      'İnsanları yanan bir binadan kurtarıyor olsaydınız ve bir kişiyi bu odadan geride bırakmak zorunda kalırsanız, kim olurdu?',
      'İç çamaşırlarını ne sıklıkla yıkıyorsun?',
      'Hiç kulak kiri tattın mı?',
      'Hiç osurup başka birini suçladın mı?',
      'Hiç terinin tadına baktın mı?',
      'Bu odadaki kim bugüne kadarki en kötü insan olurdu? Neden?',
      'Yeniden doğmuş olsaydın, hangi yüz yılda doğmak isterdin?',
      'Söylediğiniz veya yaptığınız bir şeyi silmek için zamanda geriye gidebilseydiniz, bu ne olurdu?',
      'Erkek arkadaşın veya kız arkadaşın seni hiç utandırdı mı?',
      'Birdenbire görünmez olsaydın ne yapardın?',
      'Banyoda kaldığınız en uzun süre nedir ve neden bu kadar uzun süre kaldınız?',
      'Şimdiye kadar gördüğüm en garip rüyayı anlat.',
      'Duşta işiyor musun?',
      'Hala yaptığın en çocukça şey nedir?',
      'Hangi çocuk filmini tekrar tekrar izleyebilirsin?',
      'Ayak kokunuz kötü mü?',
      'Saçma takma adların var mı?',
      'Telefonunuzda hangi uygulamada en çok zaman harcıyorsunuz?',
      'Tek bir oturuşta yediğin en çok yemek ne?',
      'Tek başınayken dans ediyor musun?',
      'Karanlıktan korkar mısın?',
      'Bütün gün evdeysen ne yapardın?',
      'Günde kaç öz çekim yapıyorsunuz?',
      'En son ne zaman dişlerini fırçaladın?',
      'En sevdiğin pijamalar neye benziyor?',
      'Hiç yerden bir şey yedin mi?',
      'Yapmaman gereken bir şeyi yaparken hiç yakalandın mı?',
      'Vücudunun hangi bölümünü seviyorsun, hangi kısmından nefret ediyorsun?',
      'Hiç bitlendin mi?',
      'Pantolonunu hiç kestin mi?',
      'Tabağını yalıyor musun?',
      'Kimsenin senin hakkında bilmediği bir şey nedir?',
      'Hiç tabağını yaladın mı?',
      'Dirseğini yalayabilir misin?',
      'Eğer buradaki herkesi yanan bir binadan kurtarmaya çalışıyor olsaydın ve birini geride bırakmak zorunda kalırsan, kimi geride bırakırdın?',
      'Telefonda aradığın son şey neydi?',
      'Hiç asansörde gaz kaçırdın mı?',
      'Bir günlüğüne karşı cins olsan ne yapardın?',
      'Banyodayken yanlışlıkla hiç kimse içeri girdi mi?',
      'Hayatınızda bir şey değiştirebilseydiniz, ne olurdu?',
      'En büyük pişmanlığın nedir?',
      'Telefonunuzdaki en utanç verici fotoğraf hangisidir?',
      'Kimsenin bulamadığı kötü bir şey yaptınız mı?',
      'Sahip olduğunuz en iğrenç alışkanlık nedir?',
      'Hiç kimseye söylemediğin bir sırrın var mı?',
      'Şimdiye kadar gördüğünüz en korkunç rüya nedir?',
      'Çorabını değiştirirken ayağını koklar mısın?',
      'Eğer herhangi bir tür hayvan olabilseydin, ne yapardın?',
      'Karanlıktan korkar mısın?',
      'Hiç yaşınız hakkında yalan söylediniz mi?',
      'En son ne zaman dişlerini fırçaladın?',
      'Kimsenin senin hakkında bilmediği bir şey nedir?',
      'Bir ilişkinizdeki en büyük korkunuz nedir?',
      'En komik ilk randevunuz neydi?',
      'En garip alışkanlığın nedir?',
      'Kaç tane çocuk sahibi olmak istersiniz?',
      'Hakkınızda bilmem gereken utanç verici bir gerçek nedir?',
      'Çocukluktaki lakabın neydi?',
      'En sevdiğiniz yemek nedir?',
      'En sevdiğiniz renkleriniz nedir ve neden?',
      'Hayalindeki meslek ne?',
      'Bir adada 3 gün sıkışıp kalırsan, ne yaparsın?',
      'En sevdiğiniz kişi kimlerdir ve neden?',
      'Tuvalet kağıdınızı ruloya nasıl koyarsınız?',
      'İlk görüşte aşka inanır mısın?',
      'Aşka inanıyor musunuz?',
      'Hayalinizdeki düğün nedir?',
      'Şansınız olursa hangi ülkede yaşamak istersiniz?',
      'En çok neyi hayal ediyorsun?',
      'Şimdiye dek yaşadığınız en garip rüyayı açıklayabilir misiniz?',
      'En büyük pişmanlığın nedir?',
      'Beni seviyor musun?',
      'Saçını yıkamadan en uzun ne kadar süre bekledin?',
      'Herhangi bir ünlü ile evlenseydin, kim olurdu?',
      'Kaç tane erkek arkadaşın 0ldu?',
      'Sizden en az 10 yaş büyük bir kişiye hiç aşık oldunuz mu?',
      'Şu an kiminle çıkıyorsun?',
      'Sevdiğiniz birinin önünde söylediğiniz veya yaptığınız en utanç verici şey nedir?',
      'Vücudunun hangi bölümünü seviyorsun, hangi kısmından nefret ediyorsun?',
      'Hayran olduğun ünlü kim?',
      'Bu odadaki biriyle bir dans gösterisi yapmak zorunda olsaydın, kimi seçerdin?',
      'Hayallerinizdeki insanla evleneceksin denilse, telefonsuz bir yıl geçirir miydiniz?',
      'Hayatınızın geri kalanında sadece tek bir saç modeli yapabilseydin, kıvırcık saçları mı yoksa düz saçları mı seçerdin?',
      'Hayatının sonuna kadar bir makyaj eşyası kullanmaman söylense hangisini seçerdin?',
      'Senden daha kısa biriyle çıkar mısın?',
      'Vücudunuzla ilgili bir şeyi değiştirebilseydin, bu ne olurdu?',
      'Okulunda başka bir kız olsaydın kim olurdun?',
      'Aynada kendine hayran hayran bakar mısın?',
      'Sevgilinle ilgili yaptığın en utanç verici şey nedir?',
      'Hiç amigo olmak istedin mi?',
      'Sınıfımızdaki en iyi 5 erkek kim? Onları sırala.',
      'Gelecekte kaç çocuk sahibi olmak istersiniz?',
      'En çok kimden nefret ediyorsun?',
      'Ünlü biriyle çıkabilseydin, kim olurdu?',
      'Issız bir adada okulumuzdan kimin mahsur kalmasını isterdiniz?',
      'Hiç terk edildin mi? Bunun nedeni neydi?',
      'Yapabilseydin kendin üzerinde değiştirebileceğin bir fiziksel özellik nedir?',
      'Şişman olmadan istediğin bir şeyi yiyebilseydin, bu yemek ne olurdu?',
      'Eğer görünmez olsaydın, bu odadan kimi gözetlemek isterdin?',
      'Okulumuzun (iş yerinin) en popüler 5 kızını sayar mısın?',
      'Bu odada kiminle çıkmak isterdin?',
      'Vücudunun en beğendiğin yeri neresidir?',
      'En son ne zaman aynaya baktın?',
      'Sevgiline hiç yalan söyledin mi?',
      'Senden daha yaşlı bir kadınla çıkar mısın?',
      'En son ne zaman ağladın?',
      'Sarışın mı seversin esmer mi?',
      'Ailen kız arkadaşından nefret ederse, onu terk eder miydin?',
      'Kız arkadaşın en iyi arkadaşından nefret ederse ne yapardın?',
      'Steroid kullandın mı?',
      'Kimi kıskanıyorsun?',
      'Sizce grubumuzdaki en çok sevilen kişi kim?',
      'Hiç bir kız tarafından ret edildin mi?',
      'Fakir ve akıllı olmak mı ya da zengin ve dilsiz olmak mı? Hangisini seçerdin?',
      'Eşine hiç yalan söyledin mi?',
      'Hiç yaşın hakkında yalan söyledin mi?',
      'Hiç ilk görüşte aşık oldun mu? Kimdi?',
      'Sevmediğin bir kız sana aşık olsaydı, ona ne söyler nasıl davranırdın?',
      'Sevdiğin ama açılamadığın kişinin başka birini sevdiğini öğrensen ne yapardın?',
      'Hiç arkadaşının sırrını başkasıyla paylaştın mı?',
      'Benim mesajımı hiç görmezden geldin mi. Neden bunu yaptın?',
      'Hiç en iyi arkadaşına yalan söyledin mi?',
      'En iyi 2 arkadaşın arasında seçim yapsan hangisini seçerdin?',
      'En iyi arkadaşının en sevmediğin huyu nedir?',
      'Sevdiğin ama açılamadığın kişi sana en yakın arkadaşını sevdiğini söylese ne yapardın?',
      'Arkadaşının sevgilisini aldattığını bilseydin ne yapardın?',
      'Kendini daha iyi biri gibi göstermek için en iyi arkadaşın hakkında yalan söyledin mi?',
      'Kim daha güzel/yakışıklı? Sen mi (odadaki herhangi biri)……. mı?',
      '[Oyundaki herhangi biri] hakkındaki ilk izleniminiz neydi?',
      'Odadaki herkese 1’den 10’a kadar puan verin, 10’u en sıcak olanı; 1 ise en kötü ve soğuk olanı.',
      'Bir diş fırçasını en iyi arkadaşınla paylaşır mısın?',
      'Arkadaşın onun için yalan söylemeni istedi ve başının derde gireceğini biliyor olsaydın yine de söyler miydin?',
      'Okuldaki en popüler kız/erkek sen olsaydın arkadaşlarından vazgeçer misin?',
      'Biri size en iyi arkadaşınızın nasıl olduğunu sorduğunda, onu nasıl anlatırdın?',
      'Bir tatil kazansan ve iki kişi getirmenize izin verilse aramızdan kimleri seçerdin?',
      'Saklamanız söylendiği bir sırrı hiç anlattınız mı?',
      'Sevgilin ve en iyi dostum göle düşse önce hangisini kurtarırsın?',
      'Aşık olduğun birinin önünde asla yapamayacağın bir şey var mı?',
      'En çok kiminle çıkmak istersin?',
      'Bu odadaki insanlardan, kiminle çıkardın?',
      'Bu odada en iyi gülüşe kim sahip?',
      'Bu odada en şirin burun kimde?',
      'Bu odada en güzel gözler kimde?',
      'Bu odadaki en komik kim?',
      'Bir kız/erkek ile buluşmaya gittiğinde aynada kendini ne sıklıkta kontrol ediyorsun?',
      'Bu odada en güzel dans eden kim?',
      'Bu odadaki birinin bir fiziksel özelliğine sahip olsaydınız, bu ne olurdu?',
      'Yaşamak için bir haftan vardı ve bu odada biriyle evlenmek zorunda olsaydın, kim olurdu?',
      'Yaşamak için sadece 24 saatiniz olsa ve bu odadaki herhangi biriyle herhangi bir şey yapabilseydiniz, kim olurdu ve o kişiyle ne yapardınız?',
      'Dünyadaki son kişi ben olsam benimle çıkar mıydın?',
      'Yaptığın en çapkın şey nedir?',
      'Bir uygulamayı telefonunuzdan silmek zorunda kalsanız hangisini silerdiniz?',
      'Bir ilişkideki en büyük korkun nedir?',
      'Odanın her bir kişi hakkında bir tane olumlu, bir tane olumsuz şey söyleyin.',
      'Sevmediğin kötü huyun var mı?',
      'Hayatında yaptığın en çılgın şey nedir?',
      'Üç gün boyunca bir adada mahsur kalmış olsaydınız, bu odadan kimleri seçerdiniz?',
      'Bu odadaki en sinir bozucu kişi kim?',
      'Bu odada biriyle evlenmek zorunda kalsan kim olurdu?',
      'En uzun ilişkiniz ne kadar sürdü?',
      'Bir ünlü Instagram’da seni takip etseydi bu ünlünün kim olmasını isterdin?',
      'Instagram’da 5 kişiyi silmek zorunda olsan kimleri silerdin?',
      'Kaç çocuk sahibi olmak ister misin?',
      'Hayallerinizdeki kişiyi tarif edin.',
      'Messi mi Ronaldo mu?',
      'Pes mi Fifa mı?',
      'İlk işin neydi?',
      'Üniversite hakkındaki en büyük korkun nedir?',
      'En iyi arkadaşının seninle aynı üniversiteye gitmesini ister misin?',
      'Mevcut erkek arkadaşının ya da kız arkadaşının seninle aynı üniversiteye gitmesini ister misin?',
      'Hayalindeki iş ne?',
      'Hiç bir dersten başarısız oldun mu?',
      'Hiç kopya çektin mi?',
      'Hiç sınıfta uyudun mu?',
      'Sınıfta asla yanında oturmak istemeyeceğin kim?',
      'Derse hiç geç kaldın mı?',
      'Bir öğretmenin önünde yaptığın en utanç verici şey nedir?',
      'Hiç masanın altına sakız attın mı?',
      'Hiç okulda kavga ettin mi?',
      'Bir sınavdan aldığın en kötü puan neydi?',
      'Sınıfta hiç uyuya kaldın mı?',
      'Hiç gözaltına alındın mı?',
      'Eğer görünmez olsaydın hangi derse gizlice girerdin?',
      'En kötü sınıf hangisidir?',
      'Karşı cins olarak uyanmak olsaydın ilk yapacağın şey nedir?',
      'Yaptığın bir şey için başkasının başının derde girmesine hiç izin verdin mi?',
      'Yaptığın en utanç verici şey ne?',
      'Birinden ayrılmanın en saçma nedeni neydi?',
      'Sahip olduğun en büyük alışkanlık nedir?',
      'Sizce en iyi özellik nedir? Ve en kötüsü nedir?',
      'Şu ana kadar yaptığın en cesur şey nedir?',
      'Turda kimi domuzda büyülemek istersin?',
      'En son ne zaman yatağa baktın?',
      'En çok ne uyumayı hayal ediyorsun?',
      'Paranızı yasadışı olarak kazanacak olsanız, nasıl yapardınız?',
      'Hala yaptığın çocukça bir şey nedir?',
      'Eğer kör olsaydın, raunttaki rehber köpeğin kim olurdu?',
      'Seni en çok ne etkileyebilir?',
      'Bundan sonra gecenin geri kalanında sadece 3 kelime kullanmanıza izin verilirse - hangisi olurdu?',
      'Diktatör olsaydınız, ilk önce hangi yasayı düzenlerdiniz?',
      'Nazi döneminde yaşamış olsaydınız, kim olurdu?',
      'Okul zamanınız / çalışma süreniz / eğitim / geçen yıldaki en utanç verici deneyim neydi?',
      'Hayatının en büyük hatası neydi?',
      'Asla ne yapmazsın - yaşamak için sadece 12 saatin olduğunu bilsen bile?',
      'Hangi suçu işledin?',
      'Bana çocukluğundan bir sır ver.',
      'En büyük (gizli) yardımcınız nedir?',
      'Benimle ne yapmak istersin … (ya da xy kişiyle), o zaman (onun, …) hafızamı silebilseydin?',
      'Şimdiye kadar yaptığın en kötü şey nedir?',
      'Kiminle kime en büyük tutundun?',
      'Hiç mevcut olanlardan birine aşık oldun mu?',
      'Eğer bir vampir olsaydın, şimdi kim ısırırdın?',
      'Şimdiye kadar yaşadığınız en kötü şey nedir?',
      'En kötü sepetiniz neydi?',
      'Pantolonunu hiç halka vurdun mu?',
      'En karanlık fantezin nedir?',
      'Başka biriyle yaşadığın en güzel şey nedir?',
      'Sizin için en büyük Abturner nedir?',
      'Vücudunda en çok neyi seviyorsun ve en çirkin olan nedir?',
      'Turumuzdan kim çıplak görmek istersiniz?',
      'Turdaki kime en çok aşık olabilirsiniz?',
      'Hiç bu raunttan birinin meydana geldiği erotik bir rüya gördünüz mü?',
      'Kendine genital bölgede dövme yaparsan - orada ne olurdu?',
      'Bir ilişkide daha önemli olan - seks mi aşk mı?',
      'Sence seks harika, iyi, tamam, bazen güzel - ya da sizin için o kadar önemli değil mi?',
      'Seni gerçekten iyi yapan ne?',
      'Haftada / ayda kaç kez seks yapıyorsun - ve ne sıklıkla seks yapmak istersin?',
      'Daha önce kaç tane seks partnerinle yattın?',
      'Vücudun hangi kısmı seni en çok etkiliyor?',
      'İlk defa nasıl, nerede ve kiminle yaptın?',
      'Genişletilmiş bir ön sevişme sizin için ne kadar önemli?',
      'Bir erkek / kadın sizi baştan çıkarmak için ne yapmalı?',
      'Hiç üçlü yaptın mı? Peki nasıl sevdin?',
      'Hiç iyi bir arkadaşla seviştin mi?',
      'Eşiniz dışında hiç bu gruptan biriyle seks yaptınız mı?',
      'Sen şimdiye dek yaşadığın en utanç verici an hangisiydi?',
      'Tamamen aşıksın ama o gidiyor. Seni çığlık atarak kaçmak için ne olacaktı?',
      'Önce kadınlarda neye önem verirsiniz - göğüsler, göt veya yüz?',
      'Bir erkekte ilk olarak neye dikkat edersiniz ve neye sahip olmanız gerektiğini düşünmelisiniz: awwwww, cool!',
      'Hiç bu raunttan birinin düşüncesiyle tatmin oldunuz mu?',
      'Seks sırasında en sevdiğin pozisyon nedir?',
      'En garip randevunda ne oldu?',
      'Seks sırasında mutlak bir tabu nedir?',
      'Yaptığın en sıcak şey ne?',
      'Hiç siber veya telefonla cinsel ilişkiye girdiniz mi - ve kiminle?',
      'En berbat gizli dileğin nedir?',
      'Daha iyi - traşlı mı traşsız mı?',
      'Bu turda kim en iyi seks yaptığını düşünüyorsun?',
      'Seninle uyumak için kime para verirdin?',
      'En çılgın seks deneyimin neydi?',
      'Hiç tehlikeli seks yaptın - ve bu tam olarak nasıldı?',
      'Hiç bir yabancıyla seks yaptın mı? örneğin Tinder’den?',
      'Hatta devam edersen - uzmanlığın ne olurdu?',
      'Kendini tatmin ettiğinde en çok neyi düşünmek istersin?',
      'Hiç aynı cinsiyetten seks yaptın mı?',
      'Benimle seks yaptın. Daha sonra bana ne söylerdin?',
      'Seni düz yatırmanın en iyi yolu nedir?',
      'Her durumda kiminle yatarsın - evli olsan da ölümsüz müsün?',
      'Hayatının en iyi seksiyle kiminle tanıştın?',
      'Hiç seks için para ödedin mi?',
      'Son ateşli rüyanı kim gördün?',
      'Hiç seks sırasında şaşırdınız mı - ve kim tarafından?',
      'En sevdiğin pozisyon nedir?',
      'Erojen bölgen nerede?',
      'Doruğa inliyor musun?',
      'Kiminle seks yapmak isterdin?',
      'En son ne zaman seks yaptın?',
      'Nerede samimi piercingler var?',
      'Kaç tane kadın / erkek öpüştün?',
      'En kötü sepetiniz neydi?',
      'En sıcak buluşma kiminle oldu?',
      'En sevdiğin pozisyon ne?',
      'İlk seferiniz ne zamandı?',
      'Hala bakiremisin?',
      'Tuvalette: Tuvalet kağıdının katlanması veya yuvarlanması?',
      'Nerede tıraş oluyorsun?',
      'Aynı anda 2 kişiyle yakın oldun mu?',
      'Hiç ablan / erkek kardeş inilti duydun mu?',
      'Hiç mastürbasyonda bulundun mu?',
      'Hangi yerlerde seks yaptın?',
      'Hiç birini aldattın mı?',
      'Her zaman sadık mısın?',
      'Ergen bir aşkın oldu mu?',
      'Hangi insanda aşıksın?',
      'Hangi ünlüyle buluşmak istersin?',
      'Hayatındaki en utanç verici an ne?',
      'Buradaki gruptan en çok hangi ağzı seviyorsun?',
      'Hangi oyuncunun en güzel elleri var?',
      'İlk öpücüğün neredeydi?',
      'Turda en çok kim öpmek istersiniz?',
      'Masada kim muhtemelen en gıdıklanır?',
      'Hayatının en büyük hatası neydi?',
      'Randevunuzda utanç verici bir şey mi oldu?',
      'Hiç uyuşturucu madde ile bağlantı kurdun mu?',
      'Şimdi hangi kişiyi öpmek isterdin?',
      'En son ne zaman takılmıştın?',
      'Hiç bir okul sınavında hile yaptın mı?',
      'Hiç geçmişte bir şey çaldın mı?',
      'Geceleri horluyor musun?',
      'Hangisi senin favori şarkın?',
      '1 hafta boyunca hangi oyuncuyla yer değiştirirsin ve neden?',
      'Yalnız bir adaya taşınıyorsun, turdan kim yanına alıyorsun?',
      'En çok neden korkuyorsun?',
      'Nerede tıraş oluyorsun?',
      'Kullanıcı adın var mı?',
      'Yıkamadan önce tuvalete mi bakıyorsun?',
      'Sana en kötü kalbi kim verdi?',
      'Kaç kez öpüştün?',
      'Başına gelen en utanç verici şey nedir?',
      'Kaç tür / kız öpüştün?',
      'Kimi seviyorsun?',
      'Hangi yıldızı sıcak seviyorsun?',
      'XY ile bir şeyler başlatır mısın (isim girin)?',
      'Hiç bir şey çaldın mı?',
      'Hangi hayvan size en uygun ve neden?',
      'En kötü randevun neydi?',
      'Şimdi kim öpmek istersin?',
      'Sırrın nedir, karanlık fantezin?',
      'Kıçına dövme yapmayı mı yoksa dilini delmeyi mi tercih edersin?',
      'Gecenizi hangi ünlü kişiyle geçirmek istersiniz?',
      'Şimdi nereye ışınlanmak istersiniz?',
      'Bir yıldızla evlenmelisin, kim?',
      'İlk öpücüğün nasıl / nerede / kiminle oldu?',
      'Hala bakiremisin?',
      'Tıraş olur musun? Evet ise nerede?',
      'Genital bölgede hangi saç stiline sahipsin?',
      'Kendi cinsiyetine sahip biriyle yakınlaşmayı merak ediyor musun?',
      'Uzun bir ön sevişmeyi seviyor musun? Eğer öyleyse, nasıl görünmeli?',
      'Kendini tatmin ettiğinde ne düşünüyorsun?',
      'İlk seferiniz ne zamandı?',
      'Hala bakiremisin?',
      'Hiç birini aldattın mı?',
      'En kötü sepetiniz neydi?',
      'Orgazm inliyor mu?',
      'Hiç mastürbasyonda bulundun mu?',
      'Hiç sütyenini doldurdun mu?',
      'En son ne zaman seks yaptın?',
      'Hangi yerlerde daha önce mastürbasyon yaptın?',
      'Kendini tatmin ettiğinde ne düşünüyorsun?',
      'Çiş tecrüben var mı?',
      'Hiç dışarıda seks yaptın mı?',
      'En sevdiğin pozisyon nedir?',
      'Her zaman sadık mıydın?',
      'Hangi kasık saç modeline sahipsin?',
      'Aynı anda 2 kişiyle yakın oldun mu?',
      'Sırrın nedir, karanlık fantezin?',
      'Suratındaki bir adam tarafından sıçramasına izin verir misin?',
      'Küçükken doktor oyunları oynadın mı?',
      'Eşcinsel deneyimleriniz oldu mu?',
      'Hiç telefon seks yaptın mı?',
      'Erotik bir iletişim reklamından vazgeçmek zorunda kalsaydınız, ne olurdu?',
      'Turda en güzel kimi buluyorsun? Tüm insanları tatlıdan çirkin hale getir.',
      'Sınıfında kimi muhtemelen öpersin?',
      'Bu raundu kimlerden sonraki partiye davet etmeyeceksiniz?',
      'Ona en son söylediğin yalan neydi?',
      'Asla söylemediğin en büyük dileğin neydi?',
      'Hangi suçu işledin?',
      'Duşta işiyor musun?',
      'Bugün ne çocukça davranışın var?',
      'Nerede tıraş oluyorsun?',
      'Hiç birini aldattın mı?',
      'Kimsenin bilmediği en büyük korkun nedir?',
      'Hiç kimsede hiçbir şey bilmeyen, kime aşık oldunuz?',
      'Hiç sütyenini ya da külotunu doldurdun mu?',
      'Çirkin ve popüler ya da hoş ve sevilmeyen olmayı tercih eder misin?',
      'En çok hangi pozisyonu seviyorsun?',
      'En büyük ve pişman olduğun kötülüğün neyle alakalı idi?',
      'Hiç kimsenin bilmediği bir şeyini bana söyler misin?',
      'En çok utandığın an ne zamandı?',
      'En son neden ağladın?',
      'Hayatta olmazsa olmaz dediğin aşırılık durumuna bir tane örnek verir misin?',
      'En çaresiz anında kimi aradın?',
      'Şu anki ruh haline bakarak ne tür film izlersin (aksiyon/dram/bilim kurgu/romantik komedi/biyografi/fantastik)',
      'Diyelim bilgi yarışmasında ödül kazandın, karşılığında üç gezi biletin var bunlar; Brezilya/ San Francisco ve Tokyo. Tercihin hangisi olurdu?',
      'Deseler ki sana “geçmişte bir anı seç ve seni oraya döndüreceğiz” Tekrar yaşamak istediğin an nedir?',
      'İç çamaşarı giyiyor musun?',
      'Bu odadakiler arasında sır tutma  konusunda en çok zorlanan kişi kimdir?',
      'Yapıpta tamamen utanç duyduğun birşeyden bahset.',
      'Vücudunun en çok hangi tarafıyla gurur duyuyorsun?',
      'Facebook’ta engelli ve kısıtlanmış kimseler listende kimler var?',
      'En kötü alışkanlığın nedir?',
      'Bu odadaki birini kölen olarak alabilme şansın olsaydı, kim olurdu ve ne yapmasını isterdin?',
      'Sana kendini ne güvensiz hissettirir?',
      'En büyük kusurun nedir?',
      'Hayatında yaptığın en büyük hata nedir?',
      'Daha önce karşı cinsten birine iç çamaşırı aldığın oldu mu?',
      'Sağ tarafındaki kişiyi öpme düşüncesi seni heyecanlandırıyor mu?',
      'İlk ne zaman öpüştün?',
      'Daha önce annenle babanı sevişirken yakaladın mı?',
      'Söylediğin en son yalan neydi?',
      'Seni en çok tahrik eden şey nedir?',
      'Alır mısın yoksa daha çok verir misin?',
      'Bize bir sarhoşluk hikayeni anlat!',
      'Sağ tarafında oturan insanın en çok hangi özelliğini sevmiyorsun?',
      'Seni en çok tahrik eden şey nedir?',
      'Daha önce gördüğün en açık seçik rüya neydi? Detayıyla açıkla!',
      'Birinin sana söylediği en son sırrı açıkla!',
      'Hiç fetişin var mı? Varsa açıkla!',
      'Bakir/bakire misin?',
      'Daha önce hiç komşudan birşey çaldın mı?',
      'Sevdiğin en sıradışı yer neresi?',
      'Bir daha asla yapmayacağın seks işini yaptın mı?',
      'Ön sevişme sırasında nelerden hoşlanırsın?',
      'Şimdiye kadar yaşadığınız en iyi orgazm hangisi?',
      'En son ne zaman mastürbasyon yaptın?',
      'En sevdiğiniz pozisyon nedir?',
      'Kendine dokunurken nasıl hissediyorsun?',
      'Karşı cins olarak uyandırırsan ilk kirli şey ne yapardın?',
      'En çılgın bir gecelik stand hikayen nedir?',
      'Baskın, itaatkâr veya tarafsız bir partneriniz olmayı mı tercih ediyorsunuz? Sebebini açıkla?',
      'Seks yaparken müzik dinlemeyi sever misin?',
      'Hiç başka bir çiftin seks yapmasını izledin mi?',
      'Gerçekte gerçekleşen en çılgın fantezi nedir?',
      'İlk seks deneyiminiz nasıldı?',
      'Seks yapmadan en uzun gittin mi?',
      'Hiç aynı cinsten birini denedin mi?',
      'Birinin sana söylediği en seksi şeyler neler?',
      'Hiç bir gecelik stand hikayen oldu mu?',
      'İnsanların seks yaptıklarına tanık oldunuz mu?',
      'Seks sırasında yaptığınız en korsan şey nedir?',
      'İnsanların seks yaptıklarına hiç tanık oldunuz mu?',
      'Seks sırasında ışıkları açmayı veya kapatmayı sever misin?',
      'Seks yapmak için en sevdiğin yer neresi?',
      'Yaramaz konuşma seni uyarıyor mu?',
      'Hiç orgazm taklidi yaptın mı?',
      'Zevk vermek ister misin?',
      'Hiç öğretmen hakkında hayal ettin mi?',
      'Birinin seni yatağa götürdüğü en hızlı şey nedir ve nasıl?',
      'Seks sırasında en sevdiğin pozisyon nedir? Sebebini açıkla?',
      'Asla yapmayacađýn cinsel eylem nedir?',
      'Gençken yakalandığın en pis şey ne?',
      'Hayatında kaç cinsel partnerin var?',
      'Yataktayken en utanç verici durumun neydi?',
      'Seks yapmanın kaba veya şehvetli olmasını ister misiniz?',
      'Bir itaatkâr mı yoksa baskın bir ortakla mı olmayı tercih edersin?',
      'Sana ilk orgazmını kim verdi?',
      'Seni seks sırasında orgazm yapan nedir?',
      'Hiç seks partisi yaptın mı?',
      'İlk kez orgazm oldu?',
      'Hiç birinin bekaretini aldın mı?',
      'Hiç üçlü yaptın mı?',
      'Hiç bağlandın mı? Hayır ise, denemek ister misiniz?',
      'Seni en çok heyecanlandıran nedir?',
      'Cinsel olarak yaptığınız en utanç verici şey nedir?',
      'En sevdiğiniz porno hangisidir?',
      'Hiç umumi tuvalette mastürbasyon yaptın mı?',
      'Vücudunda öpülmek için en sevdiğin yer neresi?',
      'En sevdiğiniz porno hangisidir?',
      'Şipşakla ilgili en sevdiğin şey nedir?',
      'En çılgın cinsel fantezin nedir?',
      'En pis sırların neler?',
      'Hiç anal seks denedin mi?',
      'Hiç seks oyuncağı kullandın mı?'
    ]
    var cesaret = [
      'İğrenç bir ses tonuyla şarkı söyle',
      'Yalandan bir şekilde 2 dakika boyunca ağla',
      'Kendi elin ile tutkulu bir şekilde öpüş',
      'Yanındaki arkadaşının sana 1 tokat atmasına izin ver',
      'Rehberinden rastgele birini ara ve sonra yanlış aradım diye kapat',
      '1 dakika boyunca bir tavukmuşsun gibi davran',
      'İnstagramda çok saçma bir şey paylaş 5 dakika sonra sil !',
      'Bugün yaptığın bir şeyle alakalı uydurma kısa, komik bir hikaye anlat',
      'Telefonunu 1 dakika boyunca karıştırmamız için bize ver',
      'Bize İnstagram mesajlarını okumamız için izin ver',
      '(2 tane zıt içecek adı söyleyip) Bu iki içeceği karıştırıp iç.',
      'Birini ara ve karadeniz şivesiyle konuş',
      '(Kişi kız ise) Yüzündeki tüm makyajını sil',
      '(Kişi erkek ise) Biraz makyaj yap',
      'Facebook’a filtresiz ve çirkin bir selfie at ve 5 dakika sonra sil',
      'Whatsapp ındaki son mesajlaşmanı bize oku',
      'Çok yüksek bir sesle 3 saniye bağır',
      '20 tane şınav çekmeye çalış',,
      'Yeri öp',
      'Sarhoş taklidi yap',
      'Hemen kısa bir aşk şiiri yazıp oku',
      'Breakdance yap',
      'Yanındaki kişiyi öp',
      'Yanındaki kişiye masaj yap',
      'Bir bardak dolusu şarabı / birayı su içer gibi iç',
      '30 saniyeliğine bir balerin gibi dans et',
      'Yüzüne çirkin ve iğrenç bir ifade ver',
      'Yere yat ve bir balık gibi davran',
      '1 dakikalığına köpek taklidi yap',
      'Rap şarkısı uydur ve söyle',
      'Yanındaki kişiye seksi şekilde bak',
      'Yanındaki kişilerden birinin kulağına çok terbiyesiz şeyler fısılda',
      'Ağız dolusu çirkin bir küfür et',
      'Aileni ara ve kötü bir şey oldu diyerek 30 saniye boyunca onları işlet',
      'Alfabeyi geriye doğru say',
      'Çiğ yumurta iç',
      'Kıyafetlerini çıkarmadan duşa gir',
      'Kendi etrafında 10 defa hızlıca dön ve düz bir çizgide yürümeye çalış',
      'Tekrar sıran gelene kadar bir maymun gibi davran',
      'Amuda kalkmaya çalış',
      'Sıra tekrar sana gelene kadar deli taklidi yap',
      'Pantolonunun içine buz at',
      '30 saniye boyunca opera şarkısı söylemeye çalış',
      'Gruptan karşı cinsten biriyle bir kıyafetini değiştir',
      'Odadaki birini baştan çıkarmaya çalış',
      'Diline acı sos damlat ya da acı biber sür',
      'Bir yemek kaşığı ketçabı tek bir lokmada ye',
      'Gözünü kırpmadan 1 dakika durmaya çalış',
      'Şuan en yakınındaki kitabı al rastgele bir sayfa seçerek ilk gördüğün cümleyi whatsapp’tan sana son yazan kişiye yaz',
      'Telefonunun galerisinden son çektiğin 5 fotoğrafı göster',
      'Yanındaki kişiyi öp',
      'Bir kalıp sabunu al ve yala',
      'Ağzında su varken şarkı söylemeye çalış',
      '2 tur boyunca oyunu gözlerin kapalı oyna',
      'Yanındaki kişinin yüzüne tükenmez kalemle bir şey çizmesine izin ver',
      '3 dakika boyunca tek ayak üzerinde bekle',
      'Çiğ soğan yemeye çalış',
      'Yabancı biriyle selfie çek',
      '3 dakika boyunca tavuk gibi davran',
      'Ailene telefon et ve neden işten (üniversiteden ya da okuldan da olabilir) atıldığınızı anlatın.',
      'En yakın dürümcüyü ara ve 300 tavuk dürüm siparişi ver. 1 dakika sonra siparişi başka yerden verdik diye iptal et.',
      'Ayak parmaklarından birini em. Eğer yapamazsan başkasının parmağını emeceksin.',
      'Telefonunu yanında ki kişiye ver. 5 dk boyunca her yere bakmak serbest.',
      'Eğer erkekse makyaj yapmasını isteyin. Eğer kızsa makyajını silmesini isteyin.',
      '1 dakika boyunca hiç müzik olmadan dans edin.',
      'Birine telefonunu ver ve istediği herhangi birine mesaj atsın.',
      'Odada ki herkesin koltuk altını koklayın.',
      'Odanın bir ucundan diğer ucuna ellerinizin üzerinde yürüyün. Gerekirse birisinden bacaklarınızı tutmasını isteyebilirsiniz.',
      'Kafanın üstünde iki yumurta kır.',
      'Önümüzdeki 5 dakika içinde birinin hayvanı olun.',
      'Elbiselerinizle bir duş alın.',
      'Size bir tokat atmak için gruptan birini seçin.',
      'Seçtiğiniz bir sosyal medya hesabınızdan çok çirkin bir fotoğrafınızı paylaşın.',
      'Mesaj yazma bölümünüzü telefonunuzdan açın gözlerinizi kapatın ve rasgele bir kişiye körü körüne bir metin gönderin.',
      '3 dakika boyunca stand-up gösteri yap.',
      '1 dakika açacağımız müzikte break dansı yap.',
      'Ayağıma masaj yap.',
      'Komşunun evine git ve muz iste.',
      'Başkasının dişlerini fırçala.',
      'Önümüzdeki 5 dakika boyunca söylediğin her şeyden sonra “mee” diyeceksin deyin',
      'İç çamaşırını çıkar (özel olarak) ve oyunun geri kalanında kafana tak.',
      'Grubun bir şarkı seçmesine ve tüm oyuncular için bir gösteri hazırlarken şarkıya dudak senkronizasyonu yapmasına izin verin.',
      'Seçtiğiniz bir oyuncuyu öp.',
      'Karşı cins olarak giyinin ve bir resmin sizden çekilmesine izin verin.',
      'Gruptaki birinin size yeni bir saç şekli vermesine izin verin.',
      'Gözlerini birbirine bağla ve diğer bir oyuncuyu kokudan tanı.',
      'Kaşlarını başka bir oyuncu tarafından sıkıca tuttur.',
      'Bütün çorapları çıkarın ve onları pantolonunuza ve / veya sütyeninize koyun.',
      'Kendini bir pislik gibi aç ve istediğin biriyle bit.',
      'Bir fahişe ya da bir fahişe gibi davranın ve birisinin sizi satın almasını sağlayın.',
      'Mutfaktan yiyeceklerle makyaj.',
      'İstediğiniz kişiyi sprey kremayla besleyin.',
      'Birini sizi köle olarak almaya ikna edin - ona uymanız gereken hizmetleri sunarak!',
      'Seçtiğiniz bir nesneyi sızdırmak.',
      'Hayalinizdeki kız / hayalinizdeki adamı mümkün olduğu kadar orijinal boyayın.',
      'Beni (iğrenç / komik / romantik) bir aşk ilanı yap.',
      'Turda bir evlenme teklifi arasından seçtiğiniz birini yapın.',
      'Giysileri xy ile değiştirin (tercihen erkeği olan bir kadın ve tersi).',
      'Kadın: sütyenini çıkar ve bana getir.',
      'Erkek: boksör şortlarını çıkar ve bana ver.',
      'Seçtiğiniz bir kişiyi fısıldamak için kulağına fısıldayarak yapmayı deneyin.',
      'Bana süpermarket / elektronik mağazası / sebze tezgahı / bayiğinden bir ürün gibi cinsel organlarını sat.',
      'Kendinizi seçtiğiniz bir kişinin kucağına koyun - veya onu kucağınıza koyun ve orgazm oynayın.',
      'Sana bir öpücük vermek için bir takım arkadaşı seç.',
      'Mümkün olduğu kadar aynı cinsiyetten birini öpüyor.',
      'Seçtiğin birini pantolonundan tut.',
      'Elimden geldiğince elimden geleni yap.',
      'Seçtiğiniz bir oyuncu oyuncunun pantolonunu açmak için dudaklarınızı ve dişlerinizi kullanın.',
      'Kötü bir hikaye anlatın ve mümkün olduğunca fazla kirli kelime kullanın.',
      'Bir takım arkadaşıyla en sevdiğin göçü göster ve her şey hakkında yorum yap.',
      'Mükemmel oral seks bir muz veya bahçe salatalık ile tanıtın.',
      'Takım arkadaşlarından birini tişörtünden olabildiğince baştan çıkarıcı ve erotik bir şekilde al ve onu göbekten kemerine kadar öp.',
      'İstediğiniz takım arkadaşının erotik bir fotoğrafını çekin.',
      'Seçtiğin birini baştan çıkarmaya çalış ve istediğin kadar uzağa git …',
      'Balkondan işemek.',
      'Striptiz düzenleyin.',
      'Bir takım arkadaşına çıplak altından bir öpücük ver.',
      'Bir muz veya salatalık alın ve mükemmel Blowob’u simüle edin.',
      'Bir sonraki içkini Ex’de iç.',
      'İç çamaşırdaki çan komşunuza sarıldı ve ses için özür diledi.',
      'Hickeyli bir oyuncu özledim.',
      'Seçtiğiniz bir arkadaşınızla erotik bir konuşma yapın.',
      'Rakibine sağına bir öpücük ver.',
      'Turuna çıplak karnını göster.',
      'Seçtiğiniz bir kişiyle 5 dakika boyunca elinizi tutun.',
      'Kendine bir takım arkadaşı tarafından bir saç modeli tarz vereyim.',
      'Seçtiğiniz bir oyuncunun ayaklarına masaj yapın.',
      '1 dakika oryantal dans yapın.',
      'Solundaki kişiyi romantik bir evlilik teklifi yap.',
      'Mevcut tüm kadınların yanaklarından bir öpücük ver.',
      'Giysileri diğer oyuncu ile doğrudan karşı karşıya getirin.',
      'Bir takım arkadaşına 2 dakikalık baş masajı uygulayın.',
      'Bir maymunu 1 tur boyunca simüle et.',
      'Ne zaman bir şey istense, önce bir surat yap.',
      'Sadece ellerini kullanmadan bir şeyler ye.',
      '1 tur boyunca Yüzüklerin Efendisi’nden Gollum oyna.',
      'Bir oyuncuyu bir aperatifle besle.',
      'Bir vücut geliştirmeci gibi 1 dakika poz verin.',
      'Saçları en iyi olan 1 dakika içinde tespit edin.',
      'Çalınan şarkıya dans edin.',
      'Yanaktan / ağzından öpmek, farklı bir cinsel insan.',
      'Bize karnını göster.',
      'Ellerini 5 dakika tut.',
      'Tişörtünü sağında / solunda duran kişi ile değiştir.',
      'Zemini yala.',
      'Yanınızdaki kişiyi, lezzetli bir şeyle besleyin.',
      'Ex’e büyük bir bardak kola iç.',
      '5 şınav yap.',
      'Takım arkadaşınız tarafından stilize edilmesine izin verin, keskin bir saç modeli bıraktı.',
      'Kişiye ne kadar iyi olduğunu söyle.',
      'Sizin için zaten iltifat almış olduğunuz bir şeyi yazın.',
      'En kötü öğretmenini tanımla.',
      'Bir şeyler ye ve yediğin en lezzetli şeymiş gibi yap.',
      'Aklınıza gelebilecek en komik yüz buruşturma.',
      'Osuruk sesleri çıkar.',
      'Bir arkadaşını ara ve hamile olduğunu söyle.',
      'Saçının en iyi koktuğunu öğren.',
      'Önce sağına gelen diğer cinsiyet kişisini öp.',
      'Kol kaslarını göster.',
      'Kişiyi soluna baştan çıkarıcı bir bakış at.',
      'Sağa 2 sıra oturan kişiye yanağından öpücük verin.',
      'İki dakika boyunca tavuk gibi davranın.',
      'Seçtiğiniz bir öğretmeni takip edin.',
      'Sağ taraftaki oyuncu her çeşit malzemeyi demletebilir ve içmen gerekir.',
      'Tişörtünü çıkar. Kadınlar da sütyen.',
      'Elinizle eşinize yapın.',
      'Eşinin memelerini yala.',
      'Eşini gözünü bağla ve onu mahvet.',
      'Eşiniz için şerit. Zaten çıplaksan, tekrar giyin ve soyun.',
      'Sağındaki oyuncu tüm düğmeleri ve fermuarları açar.',
      'Üstünü çıkar - Kadınlar da sütyen alır.',
      'Meme uçlarına tükür ve onunla masaj yap.',
      'Bir teşhirci taklit ediyorum.',
      'Bir sonraki oyun turunu çıplak geçir.',
      'Bir sonraki içkini Ex’de iç.',
      'Orgazm oynayın.',
      'Striptiz yap.',
      'Pantolonunu almak zorunda olan bir takım arkadaşı seç.',
      'Bir muz veya salatalık alın ve mükemmel Blowob’u simüle edin.',
      'Oyuncuya, yol boyunca sana bir öpücük ver.',
      'Kıyafetlerini çıkar ve cinsel organının yararlarını diğer oyunculara açıkla.',
      'Kendi memene erotik bir şekilde masaj yap.',
      'Kirli bir hikaye anlat.',
      'Bir yabancıyı ara ve telefonla seks yap.',
      'Cinsel organınızı bir ürün olarak tanımlayın.',
      'Balkondan Pinkel.',
      'Göğsünüze krem ​​sürün ve bir ekip arkadaşı tarafından yalamasına izin verin',
      'Eski sevgiline öpücük ile bir selfie gönder.',
      'Burger King’i ara ve bir sonraki McDonald’s’ın yerini sor.',
      'Kendinizi sağdaki kişi tarafından yapınız. O gözü kapalı olacak!',
      'Buzdolabına git. Kalan paketleri açıp yarısını yenmiş halde bırakın.',
      'Kolunu on saniye tuvalete koy.',
      'Bir mono-kaş boyayın ve Insta üzerine bir selfie gönderin.',
      'Anneni ara ve bir bebeğin olduğunu söyle.',
      'Karşı tarafın diline on saniye boyunca dilinizle dokunun.',
      'Bulduğunuz ilk WhatsApp grubunu yazın: “Senden bıktım!”',
      'Instagram hikayesinde tüm takipçilerinin seni neden rahatsız ettiğini açıkla.',
      'Bir kadeh zeytinyağı iç.',
      'Bir öğeyle diyalog kur ve tartışıyormuş gibi yap.',
      'Rakibinizi kucak dansı ile şaşırtın.',
      'Solundaki kişiye, kıçından bir öpücük ver.',
      'Son WhatsApp sohbetinizi tamamlayın.',
      'Alfabeyi tersten oku.',
      'Opera söyle',
      'Oyun sırasında konuşurken sürekli yanlış kişiye bak.',
      'Ellerini kullanmadan bir muz soy.',
      'Gecenin geri kalanında tuvaleti kullanmak için izin iste',
      'Gözlerini bağla, bir oyuncuyla yavaşça dans et ve dokunarak kim olduğunu tahmin et.',
      'İnsandan battaniye ol ve birini ısıt.',
      'Bir paspas veya süpürge ile dans et',
      'Solundaki kişiye seni pataklaması için yalvar.',
      'Biriyle nasıl flört edeceğini göster.',
      'Komşularına bağır: “Bir sessiz olun be!”',
      'İki kolunun üzerine tükenmez kalem ile “Ben bir eziğim” yaz',
      'Üç kişiye “Seni seviyorum” diye mesaj yolla.',
      'Sağ tarafındaki oyuncunun sana ruj sürmesine izin ver.',
      'Solundaki kişiye onunla ne yapmaktan hoşlandığını kulağına fısılda',
      'Odadan birini seç ve onun yanağını yala',
      'Erkek ise; makyaj yap. Kız ise; makyajını temizle.',
      'Önündeki insana bakarak seksi bir şekilde muz ye.',
      'Tsirtünü çıkar ve 30 saniye boyunca gömlek dansı yap.',
      'Ne tarz bir iç çamaşır giydiğini itiraf et. Sorgulanırsan; kanıtlamak bedava.',
      'Farklı türde sosları karıştır ve ortaya çıkan şeyi ye!',
      'Bebek sesiyle favori şarkını söyle!',
      'Birbiri ile öpüşmesi gereken iki kişiyi seç',
      'Telefon alarmını ertesi sabah saat 06:00’a kur',
      'Yanındaki insanın telefonunuzdaki bir kişiye müstehcen şeyler yazmasına izin verin',
      'Pencereyi aç ve sokaktaki birinin sana el sallamasını sağla',
      'Sana en yakın kişiyle iç çamaşırlarını değiştir.',
      '5 dakika içinde partnerin orgazm yapmaya çalışın.',
      'Partnerinize çıplak bir selfie gönderin.',
      'Partnerinize kafa verin.',
      'Seks kaseti yap.',
      'Bir porno videosu izleyin ve onlar gibi davranın.',
      'Striptiz yapın.',
      'Aşkını boynundan öp.',
      'Partnerinin meme uçlarını yala.',
      'Çevrimiçi bir seks oyuncağı sipariş edin.',
      'Eşinizi tek elle soyun.',
      'Partnerine masaj yap.',
      'Aşkınıza yaramaz bir kısa mesaj gönderin.',
      'Partnerinin göğsünü yala.',
      'Eşinizin vücuduna krem şanti koyun ve yalayın.',
      'Dil partnerini istediği yere öp.',
      'Partnerinizi sadece dilinizle uyandırın.',
      'Eşinizin iç çamaşırını elleriniz olmadan çıkarın.',
      'Göz bağını tak ve partnerinin istediği şeyi yapmasına izin ver.',
      'Handjob verin.',
      'Partnerine şaplak at.',
      'Çevrimiçi bir seks oyuncağı sipariş edin ve kullanarak videonuzu gönderin.',
      'Bir sonraki görüşmemizde sana ne yapmamı istediğini söyle.',
      'Bana striptiz yaptýđýnýn bir videosunu gönder.',
      'Bir dahaki sefere yeni seksi iç çamaşırı sipariş et.',
      'Bana mastürbasyon yaptığınız bir video gönderin.',
      'Beni uyandırmak için bir şey söyle.',
      'Bana küfürlü konuştuğunuzu söyleyen bir sesli mesaj gönderin.',
      'Bana seksi bir fotoğrafını gönder.',
      'Bana nasıl sevişeceğini söyle.',
      'Bana çıplak bir selfie gönderin.',
      'Bana sesli mesajla erotik bir hikaye oku.',
      'Beni ara ve aç.',
      'Bana muzla oral seks yaptýđýnýn bir videosunu gönder.'
    ]
    var dogrulukcevap = dogruluk[Math.floor(Math.random() * dogruluk.length)];
    var cesaretcevap = cesaret[Math.floor(Math.random() * cesaret.length)]

    message.channel.send('**\`Doğruluk\` mu yoksa \`cesaret\` mi? \`d\` ya da \`c\` yazarak cevaplayınız.**')
    let uwu = false;
    while (!uwu) {
        const response = await message.channel.awaitMessages(neblm => neblm.author.id === message.author.id, { max: 1, time: 30000 });
        const choice = response.first().content
        if (choice == 'doğruluk' || choice == 'd') return message.channel.send(`${dogrulukcevap}`)
        if (choice !== 'cesaret' && choice !== 'c') {
            message.channel.send(`**HATA:** Bir önceki tur bitmedi veya hatalı kod girildi.\n__Lütfen sadece **doğruluk (d)** veya **cesaret (c)** yazarak cevap veriniz.__\n*Bu arada geliştirilme aşamasında olduğum için soru önerilerinizi bekliyorum.* **Komut:** \`+dcsoru\``)
        }
        if (choice == 'cesaret' || choice == 'c') uwu = true
    }
    if (uwu) {
        message.channel.send(`${cesaretcevap}`)

    }
}

exports.conf = {
    enabled: true,
    guildOnly: true,
    aliases: ['doğruluk-cesaret'],
    permLevel: 0
};

exports.help = {
    name: 'doğrulukcesaret',
    description: 'Doğruluk cesaret oynarsınız.',
    usage: 'doğrulukcesaret'
};
